name: Docker build and deploy image
on:
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}:latest
